package io.zilker.application.constants;

public class SQLConstants {
	public static final String USER_CREATION         = "INSERT INTO USER_DETAILS (USERNAME, FIRST_NAME, LAST_NAME, USER_PASSWORD, LOCATION) VALUES (?, ?, ?, ?, ?)";
	public static final String CONTRACTOR_CREATION   = "INSERT INTO CONTRACTOR (CONTR_NAME, CNTR_PASSWORD, COMPANY_NAME, ANNUAL_REVENUE, NO_OF_CLIENT, EMAIL) VALUES (?, ?, ?, ?, ?, ?)";
	public static final String SELECT_USER_NAME      = "SELECT * FROM USER_DETAILS WHERE USERNAME = ?";
	public static final String INSERT_NEW_PROJECT    = "INSERT INTO AVAILABLE_PROJ (PROJ_NAME, LOCATION, DESCRIPTION) VALUES (?, ?, ?)";
	public static final String SELECT_AVAILABLE_PROJ = "SELECT * FROM AVAILABLE_PROJ";
	public static final String CONTRACTOR_PRESENT    = "SELECT * FROM CONTRACTOR WHERE EMAIL = ? AND CNTR_PASSWORD = ?";
	public static final String TENDER_REQUEST        = "INSERT INTO PROJ_REQUESTS (CONTR_ID, PROJ_NAME, START_DATE, END_DATE, EST_COST, LOCATION, DESCRIPTION, AVAILABLE_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String USER_LOGIN            = "SELECT * FROM USER_DETAILS WHERE USERNAME = ? AND USER_PASSWORD = ?";
	public static final String DISPLAY_PROJECTS      = "SELECT * FROM PROJECT_DETAILS";
	public static final String DISPLAY_REQUESTED_PROJ = "SELECT * FROM PROJ_REQUESTS";
	public static final String GET_REQUESTED_PROJ    = "SELECT * FROM PROJ_REQUESTS WHERE REQUEST_ID = ?";
	public static final String APPROVE_PROJECT       = "INSERT INTO PROJECT_DETAILS (PROJ_NAME, START_DATE, END_DATE, CONTR_ID, PROJ_STATUS, LOCATION, EST_COST, DESCRIPTION) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String SELECT_UNAPPROVED     = "SELECT * FROM AVAILABLE_PROJ WHERE ID = ?";
	public static final String DELETE_REQUEST        = "DELETE FROM PROJ_REQUESTS WHERE REQUEST_ID = ?";
	public static final String DELETE_AVAILABLE      = "DELETE FROM AVAILABLE_PROJ WHERE ID = ?";
	public static final String PROJ_DETAIL           = "SELECT * FROM PROJECT_DETAILS WHERE PROJ_ID = ?";
	public static final String GET_COMMENTS          = "SELECT * FROM COMMENTS WHERE PROJ_ID = ?";
	public static final String ADD_COMMENT           = "INSERT INTO COMMENTS (PROJ_ID, COMMENTS, COMMENT_DATE, USER_ID) VALUES (?, ?, ?, ?)";
	public static final String GET_USER_LOCATION     = "SELECT * FROM USER_DETAILS WHERE USER_ID = ?";
	public static final String GET_PROJ_OF_LOCATION  = "SELECT * FROM PROJECT_DETAILS WHERE LOCATION = ?";
	public static final String CONTRACTOR_PROJECT    = "SELECT * FROM PROJECT_DETAILS WHERE CONTR_ID = ?";
	public static final String GET_DELAYED_PROJ      = "SELECT * FROM PROJECT_DETAILS WHERE PROJ_STATUS = ? AND CONTR_ID = ?";
	public static final String VIEW_DELAYED_DETAIL   = "SELECT * FROM PROJECT_DETAILS WHERE PROJ_STATUS = ? AND CONTR_ID = ?";
	public static final String ADD_RESPONSE = "INSERT INTO RESPONSE (PROJ_ID, RESPONSE_TEXT) VALUES (?, ?)";
	public static final String VIEW_RESPONSE = "SELECT * FROM RESPONSE WHERE PROJ_ID = ? ORDER BY ID LIMIT 1";
	public static final String GET_DELAYED_STATUS = "SELECT * FROM PROJECT_DETAILS WHERE END_DATE < ? AND PROJ_STATUS != 'Delayed'";
	public static final String UPDATE_STATUS = "UPDATE PROJECT_DETAILS SET PROJ_STATUS = 'Delayed' WHERE PROJ_ID = ?";
	public static final String GET_COMMENT_NAME = "SELECT USERNAME FROM USER_DETAILS WHERE USER_ID = ?";
	public static final String GET_CONTR_NAME = "SELECT CONTR_NAME FROM CONTRACTOR WHERE CONTR_ID = ?";
	public static final String PROJECT_COMPLETED = "UPDATE PROJECT_DETAILS SET PROJ_STATUS = 'Completed' WHERE PROJ_ID = ?";
}
