package io.ztech.jkingsley.employeemanagementsystem.beans.types;

public enum Qualification {
	UNSCHOOLED,
	PRE_PRIMARY,
	PRIMARY,
	MIDDLE,
	SECONDARY,
	SENIOR_SECONDARY,
	BACHELOR_OF_ENGINEERING,
	BACHELOR_OF_SCIENCE,
	BACHELOR_OF_COMMERCE,
	BACHELOR_OF_COMPUTER_APPLICATION,
	MASTER_OF_ENGINEERING,
	MASTER_OF_SCIENCE,
	MASTER_OF_COMMERCE,
	MASTER_OF_COMPUTER_APPLICATION,
	DOCTOR_OF_PHILOSOPHY
}
