package io.zilker.fantasy.constants;

public class DisplayConstants {
	public static final String CONNECTION_ERROR = "Unable To Connect to DataBase\n";
	public static final String CONNECTION_CLOSE_ERROR = "Unable to Disconnnect to data base\n";
	public static final String STARTING_OPTIONS="Enter the required option\n1.Login\n2.signup\n";
	public static final String ENTER_USER_NAME = "Enter user name\n";
	public static final String ENTER_PASSWORD = "Enter the Password\n";
	public static final String ENTER_EMAIL = "Enter the Email\n";
	public static final String INVALID_CREDENTIALS = "Invalid Credentials\n";
	public static final String LOGIN_SUCESS = "Login sucess\n";
	public static final String SIGNUP_SUCESS = "Signup sucess\n";
	public static final String MAIL_INVALID = "Email invalid!.....Enter the valid Mail\n";
	public static final String DISPLAY_ADMIN_OPTIONS = "1.Schedule a new Match\n2.Start a particular match\n3.Add Players\n4.edit player ratings\n5.End a Match\n6.exit";
	public static final String ENTER_TEAM_ONE = "Enter the playing team 1\n";
	public static final String ENTER_TEAM_TWO = "Enter the playing team 2\n";
	public static final String ENTER_SCHEDULED_DATE = "Enter the Match Scheduled Date in the format of YYYY/MM/DD\n";
	public static final String ENTER_START_TIME = "Enter the Match Starting Time in the foramt HH:MM:SS\n";
	public static final String ENTER_END_TIME = "Enter the Match Ending Time in the foramt HH:MM:SS\n";
	public static final String ENTER_MATCH_CREDITS = "Enter the Match Credits\n";
	public static final String ENTER_VALID_FORMAT = "Enter correct Format\n";
	public static final String MATCH_ADD_SUCCESS = "Match Added Sucessfully\n";
	public static final String MATCH_TO_BE_DISABLED = "Enter the Match you want to start\n";
	public static final String MATCH_DISABLED = "Match Disabled\n";
	public static final String NO_MATCHES_AVAILABLE = "No Matches are Active\n";
	public static final String ENTER_PLAYER_NAME = "Enter the Name of the Player\n";
	public static final String ENTER_PLAYER_TEAM = "Enter the Team for Which he is playing\n";
	public static final String ENTER_PLAYER_TYPE = "Enter the Type of the Player\n1.Batsman\n2.Bowler\n3.AllRounder\n4.Wicket Keeper\n";
	public static final String ENTER_PLAYER_RATING = "Enter the Rating of the Player\n";
	public static final String INVALID_ROLE = "Not a vaid Role.... Enter the Correct role of the user\n";
	public static final String MODIFY_CREDIT_PLAYER_ID = "Enter the id Player you want to edit\n";
	public static final String MODIFIED_RATING = "Enter the modified rating\n";
	public static final String INVALID_RATING = "Invalid rating....Enter the proper rating\n";
	public static final String MODIFY_SUCCESS = "Rating has been modified successfully....!\n";
	public static final String DISPLAY_USER_OPTIONS = "1.Pick a team\n2.View Team\n3.Modify teams\n4.chat\n5.view Results\n6.View Most picked players 7.exit\n";
	public static final String INVALID_SELECTION = "Invalid selection.....Please enter a valid one!";
	public static final String REMAINING_CREDITS = "Credits remaining\n";
	public static final String CHAT_OPTIONS = "Enter 1 to enter message 2 to exit\n";
	public static final String ENTER_MESSAGE= "Enter the message";
	public static final String DELETE_PLAYER_OPTIONS = "Enetr 1. delete a player 2.exit\n";
	public static final String DELETE_PLAYER_ID = "Enter the id of the player you want to delete\n";
	public static final String ENTER_PLAYER_ID = "Enter  Player ID\n";
	public static final String ENTER_PLAYERS_ID = "Enter the players ID\n";
	public static final String ENTER_MATCH_ID = "Enter the match Id\n";
	public static final String DISPLAY_REMAINING = "You can pick ";
	public static final String DISPLAY_BOWLER = " Bowlers ";
	public static final String DISPLAY_BATSMEN = " Batsmen ";
	public static final String DISPLAY_ALLROUNDER = " All Rounders ";
	public static final String DISPLAY_KEEPER = " WicketKeepers \n";	
	public static final String CREDITS_COMPLETED = "Please enter a player with less than or equal to credits remaining\n";
	public static final String BATSMEN_EXCEED = "You have already selected the required number of  batsmen\n";
	public static final String BOWLER_EXCEED = "You have already selected the required number of  bowlers\n";
	public static final String KEEPER_EXCEED = "You have already selected the required number of  Keeper\n";
	public static final String ALLROUNDER_EXCEED = "You have already selected the required number of  All Rounders\n";
	public static final String ALREADY_PRESENT = "Player already Taken\n";
	public static final String DISPLAY_MATCH_COMPLETED = "Match Status have been updated sucessfully\n";
	public static final String PLAYERS_TABLE_FORMAT = "\nPlayerId PlayerName playerRole PlayerCredits\n";
	public static final Object MESSAGES_TABLE_FORMAT = "\nUserName Message InsertedTime\n";
	public static final Object MATCHES_TABLE_FORMAT = "\nMatchId Team1 Team2\n";
	
	
}
